databases:
  - name: investissement-db
    plan: free
    databaseName: investissement
    user: investissement

services:
  - type: web
    name: investissement-app
    plan: free
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investissement-db
          property: connectionString
      - key: NODE_ENV
        value: production
